server:
  port: 8010
  servlet:
    context-path: /mod

#设置服务的名称
spring:
  application:
    name: modules

  datasource:
    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 199682
    driver-class-name: com.mysql.cj.jdbc.Driver
# 解决swagger3和springboot2.6.x路径解析问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#往eureka_service端注册的地址
eureka:
  instance:
    appname: modules
  client:
    serviceUrl:
      defaultZone: http://101.35.52.122:8000/eureka/



