server:
  port: 8010
  servlet:
    context-path: /modules

#设置服务的名称
spring:
  application:
    name: modules
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://101.35.52.122:3306/management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 199682
    driver-class-name: com.mysql.cj.jdbc.Driver


# 解决swagger3和springboot2.6.x路径解析问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  redis:
    port: ${SPRING_REDIS_PORT:6379}
    host: ${SPRING_REDIS_HOST:101.35.52.122}
    database: ${SPRING_REDIS_DATABASE:2}
    #Redis服务器连接密码（默认为空）
    password: 199682
    # Redis连接超时时间
    connect-timeout: ${SPRING_REDIS_CONNECT_TIMEOUT:2000}
    # Redis读取超时时间
    timeout: ${SPRING_REDIS_READ_TIMEOUT:5000}
    jedis:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}



#往eureka_service端注册的地址
eureka:
  instance:
    appname: modules
  client:
    serviceUrl:
      defaultZone: http://101.35.52.122:8000/eureka/

logging:
  level:
    org.apache.ibatis: debug
    com.netflix.discovery: info




