server:
  # ?????
  port: 8000
eureka:
  instance:
    # eureka???????
    hostname: zzyycc-eureka-server
  client:
    # ??????????????????
    registerWithEureka: false
    # ??????????????????
    fetch-registry: false
    serviceUrl:
      # ???????
      defaultZone: http://${eureka.instance.hostname}:${server.port}
